//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpJamApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int MatchId { get; set; }
        public string TeamId { get; set; }
        public int Score { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual Team Team { get; set; }
    }
}
