//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpJamApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Player
    {
        public string Id { get; set; }
        [Display(Name = "Team Name")]
        public string TeamId { get; set; }
        [Display(Name = "Player Name")]
        public string Name { get; set; }
        public double Skill { get; set; }
        public double Agility { get; set; }
        public double Strength { get; set; }
        public double Endurance { get; set; }
        public double Aggression { get; set; }
        public double Humor { get; set; }
        public double TeamWork { get; set; }
        public double Rating { get; set; }

        [DisplayFormat(DataFormatString = "{0:N1}", ApplyFormatInEditMode = true)]
        public double Height { get; set; }

        [DisplayFormat(DataFormatString = "{0:N1}", ApplyFormatInEditMode = true)]
        public double Weight { get; set; }
        public string Description { get; set; }
        public string PictureUrl { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
